### ISSUE TITLE
ndimage.imread has been deprecated

### ISSUE THREAD

**Issue by HarshSharma12** [pderian/PyTyphoon#1]
According to [scipy's documentation](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.ndimage.imread.html), ndimage.imread has been deprecated since v1.0 and removed in 1.2.0. 

Can you please update the code to not use it?

**Comment by pderian** [comment]
Replaced `ndimage.imread` by Pillow's `Image.open`.
Thanks!
