### ISSUE TITLE
minimal 3d optical flow example

### ISSUE THREAD

**Issue by black0017** [pderian/PyTyphoon#2]
Hello @pderian and thanks for sharing the code of your research!! 

I was wondering if you can provide a minimal example for 3d dense optical flow estimation

I am curious to apply your approach in volumetric medical images. Do you think it is possible?

Best regards,

N.A.

**Comment by pderian** [comment]
Hello @black0017 ,

Typhoon was originally written for 2d dense motion estimation.

When I made pyTyphoon, an open-source minimal python version, I noticed that the wavelet library (pywavelets) that powers this implementation supports Nd transforms. Hence I wrote a few basic examples: [Homogeneous shift](https://github.com/pderian/PyTyphoon#3d-homogeneous-shift) and [Column vortex](https://github.com/pderian/PyTyphoon#3d-column-vortex).

**I have not tested it with actual 3d data**, and beware that this implementation features the data term only. I have not developed the high-order regularizers of the original version for 3D fields.

I believe you could apply it to volumetric medical images, but I doubt the results would be interesting given the lack of regularizations... Unless you develop your own. Also beware that this Python version is not efficient at all in terms of computations.

Finally, if you are looking at single-cell images, you could be interested in the works of my former colleagues of the [SERPICO team](https://team.inria.fr/serpico/).

**Comment by black0017** [comment]
@pderian Thanks a lot for your detailed answer. I am not sure that I fully understood what you say, but I really appreciate your answer. I would search for a more basic 3d implementation of dense optical flow.
